name: Release

on: 
  push:
    tags:
    - '*'

jobs:

  release_ac24_win:
    runs-on: [windows-2016]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        path: dotbim-archicad
    - name: Checkout devkits
      uses: actions/checkout@v3
      with:
        repository: kovacsv/ArchicadDevKits
        token: ${{ secrets.PAT }}
        path: ArchicadDevKits
    - name: Unzip devkit
      run: 7z x -aos "ArchicadDevKits/Win/API Development Kit 24.3009.zip" -o"dotbim-archicad/Build/AC24"
    - name: Build
      run: |
        python dotbim-archicad/Tools/build.py --acVersion "24" --devKitDir "Build/AC24/API Development Kit 24.3009" --developerId ${{ secrets.AC_MDID_DEV }} --localId ${{ secrets.AC_MDID_LOC }}
        copy "dotbim-archicad/Build/AC24/Release/DotbimExporter.apx" "dotbim-archicad/Build/AC24/Release/DotbimExporter_AC24.apx"
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dotbim-archicad/Build/AC24/Release/DotbimExporter_AC24.apx"
        draft: true
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}

  release_ac25_win:
    runs-on: [windows-2019]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        path: dotbim-archicad
    - name: Checkout devkits
      uses: actions/checkout@v3
      with:
        repository: kovacsv/ArchicadDevKits
        token: ${{ secrets.PAT }}
        path: ArchicadDevKits
    - name: Unzip devkit
      run: 7z x -aos "ArchicadDevKits/Win/API Development Kit 25.3002.zip" -o"dotbim-archicad/Build/AC25"
    - name: Build
      run: |
        python dotbim-archicad/Tools/build.py --acVersion "25" --devKitDir "Build/AC25/API Development Kit 25.3002" --developerId ${{ secrets.AC_MDID_DEV }} --localId ${{ secrets.AC_MDID_LOC }}
        copy "dotbim-archicad/Build/AC25/Release/DotbimExporter.apx" "dotbim-archicad/Build/AC25/Release/DotbimExporter_AC25.apx"
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dotbim-archicad/Build/AC25/Release/DotbimExporter_AC25.apx"
        draft: true
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
